apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  name: allowed-repos
spec:
  match:
    namespaces:
      - "cloudbees-ci"
  parameters:
    repos:
      - "gcr.io/core-workshop/"
      - "gcr.io/cloudbees-ops-gcr/"
